language: node_js

notifications:
  slack: hrgo:A958kMGqcpSfwwUkPfYwHVNC

node_js:
  - "0.10"

addons:
  sauce_connect:
    username: "rafriki_github"
    access_key: "acf3d64f-15f3-4c17-8a1a-67fbd0175412"

before_script:
  - npm install -g nightwatch

script:
  - nightwatch -e saucelabs