language: node_js

node_js:
  - "0.10"

notifications:
  slack: hrgo:68j4IFyP85dFLUqpnCN86ipz

addons:
  sauce_connect:
    username: rafriki_github
    access_key: 1905c399-4a12-4af4-888d-b04891bd3785

before_script:
  - npm install -g nightwatch

script:
  - nightwatch -e saucelabs