language: node_js

notifications:
  slack: hrgo:rBfT5PCkIuuud2xmjq6seVXu

node_js:
  - "0.10"

addons:
  sauce_connect:
    username: "rafriki_github"
    access_key: "339bd34e-ca3b-48a8-95a0-004e33434ead"

before_script:
  - npm install -g nightwatch

script:
  - nightwatch -e saucelabs