language: node_js
node_js:
  - "0.10"

addons:
  sauce_connect:
    username: "rafriki_github"
    access_key: "339bd34e-ca3b-48a8-95a0-004e33434ead"

script:
	"npm install -g nightwatch"
	"nightwatch -e saucelabs"